import type { AthleteProfile, EventDetails, FuelPlan, TimelineItem, ShoppingItem } from "./types";
import { PRODUCTS } from "./products";

// ============ CALCULATION ENGINE ============

/**
 * Weather multiplier for hydration needs
  */
  function getWeatherHydrationMultiplier(weather: string): number {
    if (weather.includes("Très chaud")) return 1.5;
      if (weather.includes("Chaud")) return 1.25;
        if (weather.includes("Tempéré")) return 1.0;
          return 0.8; // Froid
          }

          /**
           * CHO/h based on intensity and GI tolerance
            * Source: ISSN + multiple sports nutrition papers
             */
             function calculateCHOPerHour(profile: AthleteProfile, event: EventDetails): number {
               const durationH = event.targetTime;

                 // Base CHO target by duration
                   let baseCHO: number;
                     if (durationH <= 1) baseCHO = 30;
                       else if (durationH <= 2.5) baseCHO = 45;
                         else if (durationH <= 4) baseCHO = 60;
                           else if (durationH <= 6) baseCHO = 75;
                             else baseCHO = 90; // Ultra

                               // Adjust for GI tolerance
                                 const giCap = { sensitive: 45, normal: 60, robust: 90 };
                                   baseCHO = Math.min(baseCHO, giCap[profile.giTolerance]);

                                     // Sport factor (trail/running = slightly lower absorption rate)
                                       if (event.sport === "Trail" || event.sport === "Ultra-trail") {
                                           baseCHO = Math.min(baseCHO * 0.9, giCap[profile.giTolerance]);
                                             }

                                               return Math.round(baseCHO);
                                               }

                                               /**
                                                * Water needs per hour
                                                 */
                                                 function calculateWaterPerHour(profile: AthleteProfile, event: EventDetails): number {
                                                   const weatherMultiplier = getWeatherHydrationMultiplier(event.weather);
                                                     // Base: sweat rate + some replacement (we don't replace 100%)
                                                       const baseWater = profile.sweatRate * 1000 * 0.8; // 80% replacement
                                                         return Math.round(baseWater * weatherMultiplier / 50) * 50; // round to 50ml
                                                         }

                                                         /**
                                                          * Sodium needs per hour
                                                           * Salty sweaters (high sweat rate) need more sodium
                                                            */
                                                            function calculateSodiumPerHour(profile: AthleteProfile, event: EventDetails): number {
                                                              const weatherMultiplier = getWeatherHydrationMultiplier(event.weather);
                                                                // Average sodium concentration: ~900mg/L of sweat
                                                                  const baseSodium = profile.sweatRate * 900 * 0.7;
                                                                    return Math.round(baseSodium * weatherMultiplier / 50) * 50; // round to 50mg
                                                                    }

                                                                    /**
                                                                     * Select best products based on profile and duration
                                                                      */
                                                                      function selectProducts(profile: AthleteProfile, event: EventDetails) {
                                                                        const duration = event.targetTime;
                                                                          
                                                                            // Primary gel selection
                                                                              const gels = PRODUCTS.filter(p => p.category === "gel" && !profile.allergies.some(a => p.allergens.includes(a)));
                                                                                const primaryGel = gels.find(p => p.brand === "Maurten") || gels[0];
                                                                                  
                                                                                    // Caffeine gel for late race
                                                                                      const cafGel = gels.find(p => p.name.toLowerCase().includes("caf") || p.name.toLowerCase().includes("caffeine"));
                                                                                        
                                                                                          // Drink selection
                                                                                            const drinks = PRODUCTS.filter(p => (p.category === "drink" || p.category === "electrolyte") && !profile.allergies.some(a => p.allergens.includes(a)));
                                                                                              const primaryDrink = drinks.find(p => p.brand === "Tailwind") || drinks.find(p => p.brand === "Maurten") || drinks[0];
                                                                                                const electrolyte = drinks.find(p => p.category === "electrolyte");
                                                                                                  
                                                                                                    // Bar for long efforts
                                                                                                      const bars = PRODUCTS.filter(p => p.category === "bar" && !profile.allergies.some(a => p.allergens.includes(a)));
                                                                                                        const primaryBar = bars.find(p => p.brand === "Maurten") || bars[0];

                                                                                                          return { primaryGel, cafGel, primaryDrink, electrolyte, primaryBar, duration };
                                                                                                          }

                                                                                                          /**
                                                                                                           * Build detailed timeline
                                                                                                            */
                                                                                                            function buildTimeline(
                                                                                                              profile: AthleteProfile,
                                                                                                                event: EventDetails,
                                                                                                                  choPerHour: number,
                                                                                                                    waterPerHour: number,
                                                                                                                      sodiumPerHour: number
                                                                                                                      ): TimelineItem[] {
                                                                                                                        const timeline: TimelineItem[] = [];
                                                                                                                          const durationMin = Math.round(event.targetTime * 60);
                                                                                                                            const { primaryGel, cafGel, primaryDrink, electrolyte, primaryBar, duration } = selectProducts(profile, event);

                                                                                                                              // Gel CHO per unit
                                                                                                                                const gelCHO = primaryGel?.cho_per_unit || 25;
                                                                                                                                  
                                                                                                                                    // Hydration cadence: every 15 min
                                                                                                                                      const waterPerCadence = Math.round(waterPerHour / 4); // every 15min
                                                                                                                                        
                                                                                                                                          // Gel interval (aim for target CHO/h)
                                                                                                                                            // Average ~25g CHO per gel
                                                                                                                                              const gelsPerHour = choPerHour / gelCHO;
                                                                                                                                                const gelIntervalMin = Math.round(60 / gelsPerHour);
                                                                                                                                                  
                                                                                                                                                    // If using drink mix for some CHO, reduce gels
                                                                                                                                                      const drinkCHO = primaryDrink?.cho_per_unit || 0;
                                                                                                                                                        const drinkWater = primaryDrink?.water_per_unit || 500;
                                                                                                                                                          
                                                                                                                                                            // Build timeline every 15 minutes
                                                                                                                                                              for (let min = 15; min <= durationMin; min += 15) {
                                                                                                                                                                  const hour = min / 60;
                                                                                                                                                                      const isGelTime = gelIntervalMin > 0 && min % gelIntervalMin < 15;
                                                                                                                                                                          const isBarTime = duration >= 4 && (min === 90 || (min > 90 && (min - 90) % 90 === 0)) && min < durationMin * 0.8;
                                                                                                                                                                              const isCafGelTime = cafGel && duration >= 3 && min >= durationMin * 0.6 && min % gelIntervalMin < 15;
                                                                                                                                                                                  
                                                                                                                                                                                      // Water / electrolyte sip every 15 min
                                                                                                                                                                                          if (min % 15 === 0) {
                                                                                                                                                                                                // Major hydration every 30 min
                                                                                                                                                                                                      if (min % 30 === 0) {
                                                                                                                                                                                                              const isStartHalf = min <= durationMin / 2;
                                                                                                                                                                                                                      timeline.push({
                                                                                                                                                                                                                                timeMin: min,
                                                                                                                                                                                                                                          product: primaryDrink ? primaryDrink.name : "Eau + électrolytes",
                                                                                                                                                                                                                                                    productId: primaryDrink?.id || "water",
                                                                                                                                                                                                                                                              quantity: `${waterPerCadence * 2}ml`,
                                                                                                                                                                                                                                                                        type: "drink",
                                                                                                                                                                                                                                                                                  cho: primaryDrink ? Math.round(primaryDrink.cho_per_unit * (waterPerCadence * 2 / drinkWater)) : 0,
                                                                                                                                                                                                                                                                                            water: waterPerCadence * 2,
                                                                                                                                                                                                                                                                                                      sodium: primaryDrink ? Math.round((primaryDrink.sodium_per_unit || 0) * (waterPerCadence * 2 / drinkWater)) : 0,
                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                            // Caffeine gel in last 40% of race
                                                                                                                                                                                                                                                                                                                                if (isCafGelTime && cafGel) {
                                                                                                                                                                                                                                                                                                                                      timeline.push({
                                                                                                                                                                                                                                                                                                                                              timeMin: min,
                                                                                                                                                                                                                                                                                                                                                      product: cafGel.name,
                                                                                                                                                                                                                                                                                                                                                              productId: cafGel.id,
                                                                                                                                                                                                                                                                                                                                                                      quantity: "1 gel",
                                                                                                                                                                                                                                                                                                                                                                              type: "gel",
                                                                                                                                                                                                                                                                                                                                                                                      cho: cafGel.cho_per_unit,
                                                                                                                                                                                                                                                                                                                                                                                              sodium: cafGel.sodium_per_unit,
                                                                                                                                                                                                                                                                                                                                                                                                      alert: "⚡ Caféine — boost final",
                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                    // Regular gel
                                                                                                                                                                                                                                                                                                                                                                                                                        else if (isGelTime && primaryGel && !isCafGelTime) {
                                                                                                                                                                                                                                                                                                                                                                                                                              timeline.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                      timeMin: min,
                                                                                                                                                                                                                                                                                                                                                                                                                                              product: primaryGel.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      productId: primaryGel.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              quantity: "1 gel",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type: "gel",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cho: primaryGel.cho_per_unit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sodium: primaryGel.sodium_per_unit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Bar for long efforts
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isBarTime && primaryBar) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              timeline.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      timeMin: min,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              product: primaryBar.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      productId: primaryBar.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              quantity: "1 barre",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type: "bar",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cho: primaryBar.cho_per_unit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sodium: primaryBar.sodium_per_unit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alert: duration >= 6 ? "🍫 Solide — estomac au repos" : undefined,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Sort by time, deduplicate times by offsetting
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              timeline.sort((a, b) => a.timeMin - b.timeMin);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Adjust dupes: if two items at same time, offset by 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for (let i = 1; i < timeline.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (timeline[i].timeMin === timeline[i-1].timeMin) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            timeline[i].timeMin += 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return timeline;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * Build shopping list from timeline
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function buildShoppingList(timeline: TimelineItem[]): ShoppingItem[] {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const counts: Record<string, number> = {};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          for (const item of timeline) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (item.productId === "water") continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  counts[item.productId] = (counts[item.productId] || 0) + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return Object.entries(counts).map(([productId, quantity]) => ({ productId, quantity }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * Main calculation entry point
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export function calculateFuelPlan(profile: AthleteProfile, event: EventDetails): FuelPlan {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const choPerHour = calculateCHOPerHour(profile, event);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const waterPerHour = calculateWaterPerHour(profile, event);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const sodiumPerHour = calculateSodiumPerHour(profile, event);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const totalCalories = Math.round(choPerHour * 4 * event.targetTime); // 4 kcal/g CHO approx

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const timeline = buildTimeline(profile, event, choPerHour, waterPerHour, sodiumPerHour);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const shoppingList = buildShoppingList(timeline);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const warnings: string[] = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (profile.giTolerance === "sensitive" && choPerHour > 45) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            warnings.push("⚠️ CHO/h élevé pour une tolérance GI sensible — tester à l'entraînement");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (event.targetTime > 8 && !profile.allergies.includes("real-food")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    warnings.push("💡 Pour les ultra, intégrer de la vraie nourriture (bananes, dattes) aux ravitaillements");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (event.weather.includes("Très chaud")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            warnings.push("🌡 Chaleur extrême — anticiper les ravitaillements eau, ajouter électrolytes");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { choPerHour, waterPerHour, sodiumPerHour, totalCalories, timeline, shoppingList, warnings };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * Format elapsed time in HH:MM:SS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export function formatTime(ms: number): string {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const totalSeconds = Math.floor(ms / 1000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const h = Math.floor(totalSeconds / 3600);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const m = Math.floor((totalSeconds % 3600) / 60);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const s = totalSeconds % 60;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * Find next upcoming item in timeline given elapsed time in minutes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export function getNextItems(timeline: TimelineItem[], elapsedMin: number): {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                overdue: TimelineItem[];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  next: TimelineItem | null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    upcoming: TimelineItem[];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const overdue = timeline.filter(item => item.timeMin <= elapsedMin);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const future = timeline.filter(item => item.timeMin > elapsedMin);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              overdue,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  next: future[0] || null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      upcoming: future.slice(1, 4),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }