import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  { id: "maurten-gel-100", name: "Gel 100", brand: "Maurten", category: "gel", cho_per_unit: 25, sodium_per_unit: 55, calories_per_unit: 100, price_per_unit: 3.50, weight_g: 40, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Gel hydrogel sans arôme, 25g CHO" },
    { id: "maurten-gel-100-caf", name: "Gel 100 CAF 100", brand: "Maurten", category: "gel", cho_per_unit: 25, sodium_per_unit: 55, calories_per_unit: 100, price_per_unit: 4.00, weight_g: 40, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Gel hydrogel avec 100mg caféine" },
      { id: "sis-go-gel", name: "GO Energy Gel", brand: "Science in Sport", category: "gel", cho_per_unit: 22, sodium_per_unit: 115, calories_per_unit: 87, price_per_unit: 1.80, weight_g: 60, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Gel isotonique avec eau, multiple saveurs" },
        { id: "sis-go-gel-caf", name: "GO Energy + Caffeine Gel", brand: "Science in Sport", category: "gel", cho_per_unit: 22, sodium_per_unit: 115, calories_per_unit: 87, price_per_unit: 2.00, weight_g: 60, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "75mg caféine, idéal fin de course" },
          { id: "naak-gel-vegan", name: "Energy Gel Ultra Vegan", brand: "Näak", category: "gel", cho_per_unit: 25, sodium_per_unit: 50, calories_per_unit: 100, price_per_unit: 2.90, weight_g: 65, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Version végane sans protéine d'insecte" },
            { id: "gu-gel", name: "Roctane Energy Gel", brand: "GU Energy", category: "gel", cho_per_unit: 21, sodium_per_unit: 125, calories_per_unit: 100, price_per_unit: 2.20, weight_g: 32, allergens: [], diet_tags: [], description: "Avec acides aminés, multiple saveurs" },
              { id: "spring-gel", name: "Spring Energy Gel", brand: "Spring Energy", category: "gel", cho_per_unit: 28, sodium_per_unit: 80, calories_per_unit: 120, price_per_unit: 3.50, weight_g: 45, allergens: [], diet_tags: ["real-food", "vegan"], description: "Vraie nourriture sous forme de gel" },
                { id: "maurten-drink-mix-160", name: "Drink Mix 160", brand: "Maurten", category: "drink", cho_per_unit: 40, water_per_unit: 500, sodium_per_unit: 115, calories_per_unit: 160, price_per_unit: 4.50, weight_g: 50, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Boisson hydrogel 40g CHO pour 500ml" },
                  { id: "maurten-drink-mix-320", name: "Drink Mix 320", brand: "Maurten", category: "drink", cho_per_unit: 80, water_per_unit: 500, sodium_per_unit: 230, calories_per_unit: 320, price_per_unit: 5.50, weight_g: 80, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Haute concentration 80g CHO pour 500ml" },
                    { id: "tailwind-endurance", name: "Endurance Fuel", brand: "Tailwind", category: "drink", cho_per_unit: 50, water_per_unit: 700, sodium_per_unit: 310, calories_per_unit: 200, price_per_unit: 3.50, weight_g: 54, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Tout-en-un : CHO + électrolytes" },
                      { id: "tailwind-caffeinated", name: "Caffeinated Endurance Fuel", brand: "Tailwind", category: "drink", cho_per_unit: 50, water_per_unit: 700, sodium_per_unit: 310, calories_per_unit: 200, price_per_unit: 3.80, weight_g: 54, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "35mg caféine naturelle par portion" },
                        { id: "sis-go-electrolyte", name: "GO Electrolyte", brand: "Science in Sport", category: "drink", cho_per_unit: 36, water_per_unit: 500, sodium_per_unit: 165, calories_per_unit: 144, price_per_unit: 2.50, weight_g: 50, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Boisson isotonique classique" },
                          { id: "precision-hydration-500", name: "PH 500 Electrolyte", brand: "Precision Hydration", category: "electrolyte", cho_per_unit: 0, water_per_unit: 500, sodium_per_unit: 500, calories_per_unit: 10, price_per_unit: 1.50, weight_g: 8, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Électrolytes purs, haute teneur sodium" },
                            { id: "precision-hydration-1000", name: "PH 1000 Electrolyte", brand: "Precision Hydration", category: "electrolyte", cho_per_unit: 0, water_per_unit: 500, sodium_per_unit: 1000, calories_per_unit: 10, price_per_unit: 1.80, weight_g: 8, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Ultra haute teneur sodium, chaleur extrême" },
                              { id: "naak-drink", name: "Energy Drink Ultra", brand: "Näak", category: "drink", cho_per_unit: 45, water_per_unit: 500, sodium_per_unit: 200, calories_per_unit: 180, price_per_unit: 3.20, weight_g: 50, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Avec électrolytes et vitamines" },
                                { id: "clif-bar", name: "CLIF BAR Original", brand: "Clif Bar", category: "bar", cho_per_unit: 45, sodium_per_unit: 140, calories_per_unit: 250, price_per_unit: 2.80, weight_g: 68, allergens: ["oats", "soy"], diet_tags: ["vegan"], description: "Barre endurance classique" },
                                  { id: "sis-go-bar", name: "GO Energy Bar", brand: "Science in Sport", category: "bar", cho_per_unit: 46, sodium_per_unit: 55, calories_per_unit: 230, price_per_unit: 2.20, weight_g: 65, allergens: ["oats"], diet_tags: ["vegan", "gluten-free"], description: "Barre légère, facile à digérer" },
                                    { id: "maurten-solid-160", name: "Solid 160", brand: "Maurten", category: "bar", cho_per_unit: 40, sodium_per_unit: 75, calories_per_unit: 160, price_per_unit: 4.00, weight_g: 38, allergens: ["oats"], diet_tags: ["vegan"], description: "Biscuit hydrogel Maurten" },
                                      { id: "gu-chews", name: "Energy Chews", brand: "GU Energy", category: "chew", cho_per_unit: 11, sodium_per_unit: 35, calories_per_unit: 45, price_per_unit: 0.50, weight_g: 10, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Chew individuel, facile à doser" },
                                        { id: "skratch-chews", name: "Sport Energy Chews", brand: "Skratch Labs", category: "chew", cho_per_unit: 10, sodium_per_unit: 30, calories_per_unit: 40, price_per_unit: 0.45, weight_g: 10, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Fraise naturelle, faible en sucre" },
                                          { id: "banana", name: "Banane", brand: "Nature", category: "real-food", cho_per_unit: 27, sodium_per_unit: 1, calories_per_unit: 105, price_per_unit: 0.30, weight_g: 120, allergens: [], diet_tags: ["vegan", "gluten-free", "real-food"], description: "Fruit naturel, potassium + CHO" },
                                            { id: "medjool-dates", name: "Dattes Medjool (3)", brand: "Nature", category: "real-food", cho_per_unit: 40, sodium_per_unit: 2, calories_per_unit: 160, price_per_unit: 0.80, weight_g: 60, allergens: [], diet_tags: ["vegan", "gluten-free", "real-food"], description: "Energie dense et naturelle" },
                                            ];

                                            export function getProductsByCategory(category: Product["category"]): Product[] {
                                              return PRODUCTS.filter(p => p.category === category);
                                              }

                                              export function getProductById(id: string): Product | undefined {
                                                return PRODUCTS.find(p => p.id === id);
                                                }