import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  // ===== GELS =====
    { id: "maurten-gel-100", name: "Gel 100", brand: "Maurten", category: "gel", cho_per_unit: 25, sodium_per_unit: 55, calories_per_unit: 100, price_per_unit: 3.50, weight_g: 40, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Gel hydrogel sans arôme, 25g CHO" },
      { id: "maurten-gel-100-caf", name: "Gel 100 CAF 100", brand: "Maurten", category: "gel", cho_per_unit: 25, sodium_per_unit: 55, calories_per_unit: 100, price_per_unit: 4.00, weight_g: 40, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Gel hydrogel avec 100mg caféine" },
        { id: "sis-go-gel", name: "GO Energy Gel", brand: "Science in Sport", category: "gel", cho_per_unit: 22, sodium_per_unit: 115, calories_per_unit: 87, price_per_unit: 1.80, weight_g: 60, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Gel isotonique avec eau, multiple saveurs" },
          { id: "sis-go-gel-caf", name: "GO Energy + Caffeine Gel", brand: "Science in Sport", category: "gel", cho_per_unit: 22, sodium_per_unit: 115, calories_per_unit: 87, price_per_unit: 2.00, weight_g: 60, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "75mg caféine, idéal fin de course" },
            { id: "naak-gel-vegan", name: "Energy Gel Ultra Vegan", brand: "Näak", category: "gel", cho_per_unit: 25, sodium_per_unit: 50, calories_per_unit: 100, price_per_unit: 2.90, weight_g: 65, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Version végane sans protéine d'insecte" },
              { id: "naak-gel-cricket", name: "Energy Gel Ultra Cricket", brand: "Näak", category: "gel", cho_per_unit: 23, sodium_per_unit: 50, calories_per_unit: 110, price_per_unit: 3.20, weight_g: 65, allergens: ["cricket-protein"], diet_tags: ["gluten-free"], description: "Avec protéine de cricket, 5g protéines" },
                { id: "gu-gel", name: "Roctane Energy Gel", brand: "GU Energy", category: "gel", cho_per_unit: 21, sodium_per_unit: 125, calories_per_unit: 100, price_per_unit: 2.20, weight_g: 32, allergens: [], diet_tags: [], description: "Avec acides aminés, multiple saveurs" },
                  { id: "gu-gel-original", name: "Original Energy Gel", brand: "GU Energy", category: "gel", cho_per_unit: 22, sodium_per_unit: 60, calories_per_unit: 100, price_per_unit: 1.80, weight_g: 32, allergens: [], diet_tags: ["vegan"], description: "Gel classique, saveurs variées" },
                    { id: "gu-gel-caf", name: "Roctane Energy Gel Caffeinated", brand: "GU Energy", category: "gel", cho_per_unit: 21, sodium_per_unit: 125, calories_per_unit: 100, price_per_unit: 2.40, weight_g: 32, allergens: [], diet_tags: [], description: "35mg caféine + acides aminés" },
                      { id: "spring-gel", name: "Spring Energy Gel", brand: "Spring Energy", category: "gel", cho_per_unit: 28, sodium_per_unit: 80, calories_per_unit: 120, price_per_unit: 3.50, weight_g: 45, allergens: [], diet_tags: ["real-food", "vegan"], description: "Vraie nourriture sous forme de gel" },
                        { id: "spring-gel-hill-aid", name: "Hill Aid", brand: "Spring Energy", category: "gel", cho_per_unit: 26, sodium_per_unit: 90, calories_per_unit: 115, price_per_unit: 3.80, weight_g: 45, allergens: [], diet_tags: ["real-food", "vegan"], description: "Riz brun + betterave + gingembre" },
                          { id: "skratch-gel", name: "Energy Chews Gel", brand: "Skratch Labs", category: "gel", cho_per_unit: 20, sodium_per_unit: 80, calories_per_unit: 80, price_per_unit: 2.20, weight_g: 35, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Base fruit, sans arômes artificiels" },
                            { id: "torq-gel", name: "Energy Gel", brand: "TORQ", category: "gel", cho_per_unit: 28, sodium_per_unit: 45, calories_per_unit: 116, price_per_unit: 1.90, weight_g: 45, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "2:1 maltodextrine:fructose" },
                              { id: "torq-gel-caf", name: "Energy Gel Caffeinated", brand: "TORQ", category: "gel", cho_per_unit: 28, sodium_per_unit: 45, calories_per_unit: 116, price_per_unit: 2.10, weight_g: 45, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "89mg caféine + guarana" },
                                { id: "powerbar-gel", name: "PowerGel Hydro", brand: "PowerBar", category: "gel", cho_per_unit: 27, sodium_per_unit: 200, calories_per_unit: 111, price_per_unit: 1.70, weight_g: 67, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Gel liquide avec électrolytes intégrés" },
                                  { id: "clif-gel", name: "Shot Energy Gel", brand: "Clif Bar", category: "gel", cho_per_unit: 25, sodium_per_unit: 50, calories_per_unit: 100, price_per_unit: 1.60, weight_g: 34, allergens: [], diet_tags: ["vegan"], description: "Gel classique, multiple saveurs" },
                                    { id: "clif-gel-caf", name: "Shot Energy Gel Double Espresso", brand: "Clif Bar", category: "gel", cho_per_unit: 25, sodium_per_unit: 50, calories_per_unit: 100, price_per_unit: 1.80, weight_g: 34, allergens: [], diet_tags: ["vegan"], description: "100mg caféine naturelle" },
                                      { id: "overstim-gel", name: "Antésite+ Gel", brand: "Overstim.s", category: "gel", cho_per_unit: 22, sodium_per_unit: 30, calories_per_unit: 88, price_per_unit: 1.50, weight_g: 34, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Marque française, saveur réglisse" },

                                        // ===== BOISSONS =====
                                          { id: "maurten-drink-mix-160", name: "Drink Mix 160", brand: "Maurten", category: "drink", cho_per_unit: 40, water_per_unit: 500, sodium_per_unit: 115, calories_per_unit: 160, price_per_unit: 4.50, weight_g: 50, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Boisson hydrogel 40g CHO pour 500ml" },
                                            { id: "maurten-drink-mix-320", name: "Drink Mix 320", brand: "Maurten", category: "drink", cho_per_unit: 80, water_per_unit: 500, sodium_per_unit: 230, calories_per_unit: 320, price_per_unit: 5.50, weight_g: 80, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Haute concentration 80g CHO pour 500ml" },
                                              { id: "tailwind-endurance", name: "Endurance Fuel", brand: "Tailwind", category: "drink", cho_per_unit: 50, water_per_unit: 700, sodium_per_unit: 310, calories_per_unit: 200, price_per_unit: 3.50, weight_g: 54, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Tout-en-un : CHO + électrolytes" },
                                                { id: "tailwind-caffeinated", name: "Caffeinated Endurance Fuel", brand: "Tailwind", category: "drink", cho_per_unit: 50, water_per_unit: 700, sodium_per_unit: 310, calories_per_unit: 200, price_per_unit: 3.80, weight_g: 54, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "35mg caféine naturelle par portion" },
                                                  { id: "sis-go-electrolyte", name: "GO Electrolyte", brand: "Science in Sport", category: "drink", cho_per_unit: 36, water_per_unit: 500, sodium_per_unit: 165, calories_per_unit: 144, price_per_unit: 2.50, weight_g: 50, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Boisson isotonique classique" },
                                                    { id: "sis-beta-fuel", name: "Beta Fuel", brand: "Science in Sport", category: "drink", cho_per_unit: 80, water_per_unit: 500, sodium_per_unit: 300, calories_per_unit: 320, price_per_unit: 4.50, weight_g: 84, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "2:1 maltodextrine:fructose, ultra haute énergie" },
                                                      { id: "naak-drink", name: "Energy Drink Ultra", brand: "Näak", category: "drink", cho_per_unit: 45, water_per_unit: 500, sodium_per_unit: 200, calories_per_unit: 180, price_per_unit: 3.20, weight_g: 50, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Avec électrolytes et vitamines" },
                                                        { id: "skratch-hydration", name: "Sport Hydration Mix", brand: "Skratch Labs", category: "drink", cho_per_unit: 21, water_per_unit: 500, sodium_per_unit: 380, calories_per_unit: 80, price_per_unit: 2.00, weight_g: 35, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Boisson légère, haute teneur sodium" },
                                                          { id: "skratch-super-high-carb", name: "Super High Carb Mix", brand: "Skratch Labs", category: "drink", cho_per_unit: 65, water_per_unit: 500, sodium_per_unit: 200, calories_per_unit: 260, price_per_unit: 3.80, weight_g: 70, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "70g CHO / 500ml, ultra endurance" },
                                                            { id: "torq-drink", name: "Energy Drink", brand: "TORQ", category: "drink", cho_per_unit: 46, water_per_unit: 500, sodium_per_unit: 168, calories_per_unit: 188, price_per_unit: 2.80, weight_g: 50, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "2:1 ratio, goût fruité naturel" },
                                                              { id: "powerbar-isoactive", name: "IsoActive", brand: "PowerBar", category: "drink", cho_per_unit: 36, water_per_unit: 500, sodium_per_unit: 250, calories_per_unit: 148, price_per_unit: 2.20, weight_g: 46, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "5 électrolytes, isotonique certifié" },
                                                                { id: "overstim-boisson", name: "Boisson Longue Distance", brand: "Overstim.s", category: "drink", cho_per_unit: 42, water_per_unit: 500, sodium_per_unit: 220, calories_per_unit: 168, price_per_unit: 2.40, weight_g: 50, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Formule longue distance française" },

                                                                  // ===== ÉLECTROLYTES =====
                                                                    { id: "precision-hydration-500", name: "PH 500 Electrolyte", brand: "Precision Hydration", category: "electrolyte", cho_per_unit: 0, water_per_unit: 500, sodium_per_unit: 500, calories_per_unit: 10, price_per_unit: 1.50, weight_g: 8, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Électrolytes purs, haute teneur sodium" },
                                                                      { id: "precision-hydration-1000", name: "PH 1000 Electrolyte", brand: "Precision Hydration", category: "electrolyte", cho_per_unit: 0, water_per_unit: 500, sodium_per_unit: 1000, calories_per_unit: 10, price_per_unit: 1.80, weight_g: 8, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Ultra haute teneur sodium, chaleur extrême" },
                                                                        { id: "precision-hydration-1500", name: "PH 1500 Electrolyte", brand: "Precision Hydration", category: "electrolyte", cho_per_unit: 0, water_per_unit: 500, sodium_per_unit: 1500, calories_per_unit: 10, price_per_unit: 2.00, weight_g: 8, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Max sodium, ultra-trail chaleur" },
                                                                          { id: "nuun-sport", name: "Sport Electrolyte Tablet", brand: "Nuun", category: "electrolyte", cho_per_unit: 4, water_per_unit: 500, sodium_per_unit: 300, calories_per_unit: 15, price_per_unit: 0.80, weight_g: 6, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Pastille effervescente, légère" },
                                                                            { id: "nuun-endurance", name: "Endurance Electrolyte", brand: "Nuun", category: "electrolyte", cho_per_unit: 30, water_per_unit: 500, sodium_per_unit: 380, calories_per_unit: 120, price_per_unit: 1.20, weight_g: 14, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "CHO + électrolytes, format sachet" },
                                                                              { id: "salt-stick-caps", name: "Fastchews", brand: "SaltStick", category: "electrolyte", cho_per_unit: 2, water_per_unit: 0, sodium_per_unit: 215, calories_per_unit: 10, price_per_unit: 0.60, weight_g: 4, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Capsule sel mâchable, sans eau" },
                                                                                { id: "high5-electrolyte", name: "Zero Electrolyte Tablet", brand: "HIGH5", category: "electrolyte", cho_per_unit: 0, water_per_unit: 500, sodium_per_unit: 280, calories_per_unit: 5, price_per_unit: 0.60, weight_g: 5, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Zéro sucre, zéro calorie" },

                                                                                  // ===== BARRES =====
                                                                                    { id: "clif-bar", name: "CLIF BAR Original", brand: "Clif Bar", category: "bar", cho_per_unit: 45, sodium_per_unit: 140, calories_per_unit: 250, price_per_unit: 2.80, weight_g: 68, allergens: ["oats", "soy"], diet_tags: ["vegan"], description: "Barre endurance classique" },
                                                                                      { id: "clif-bar-bloks", name: "Shot Bloks Energy Chews", brand: "Clif Bar", category: "chew", cho_per_unit: 24, sodium_per_unit: 70, calories_per_unit: 100, price_per_unit: 0.80, weight_g: 18, allergens: [], diet_tags: ["vegan"], description: "3 blocs par portion, facile à doser" },
                                                                                        { id: "sis-go-bar", name: "GO Energy Bar", brand: "Science in Sport", category: "bar", cho_per_unit: 46, sodium_per_unit: 55, calories_per_unit: 230, price_per_unit: 2.20, weight_g: 65, allergens: ["oats"], diet_tags: ["vegan", "gluten-free"], description: "Barre légère, facile à digérer" },
                                                                                          { id: "maurten-solid-160", name: "Solid 160", brand: "Maurten", category: "bar", cho_per_unit: 40, sodium_per_unit: 75, calories_per_unit: 160, price_per_unit: 4.00, weight_g: 38, allergens: ["oats"], diet_tags: ["vegan"], description: "Biscuit hydrogel Maurten" },
                                                                                            { id: "naak-bar-cricket", name: "Ultra Bar Cricket", brand: "Näak", category: "bar", cho_per_unit: 35, sodium_per_unit: 100, calories_per_unit: 200, price_per_unit: 3.50, weight_g: 50, allergens: ["cricket-protein", "oats"], diet_tags: [], description: "10g protéines, endurance longue durée" },
                                                                                              { id: "naak-bar-vegan", name: "Ultra Bar Vegan", brand: "Näak", category: "bar", cho_per_unit: 36, sodium_per_unit: 95, calories_per_unit: 195, price_per_unit: 3.20, weight_g: 50, allergens: ["oats"], diet_tags: ["vegan", "gluten-free"], description: "Protéine végétale, goût fruits rouges" },
                                                                                                { id: "spring-bar", name: "Real Food Bar", brand: "Spring Energy", category: "bar", cho_per_unit: 38, sodium_per_unit: 85, calories_per_unit: 200, price_per_unit: 4.00, weight_g: 55, allergens: [], diet_tags: ["real-food", "vegan"], description: "Ingrédients entiers, riz + haricots" },
                                                                                                  { id: "torq-bar", name: "Organic Energy Bar", brand: "TORQ", category: "bar", cho_per_unit: 44, sodium_per_unit: 60, calories_per_unit: 220, price_per_unit: 2.50, weight_g: 65, allergens: ["oats"], diet_tags: ["vegan"], description: "Bio certifié, saveurs naturelles" },
                                                                                                    { id: "powerbar-performance", name: "Performance Energy Bar", brand: "PowerBar", category: "bar", cho_per_unit: 42, sodium_per_unit: 90, calories_per_unit: 230, price_per_unit: 2.30, weight_g: 65, allergens: ["oats", "soy"], diet_tags: [], description: "C2MAX dual source carbs" },
                                                                                                      { id: "larabar-date", name: "LÄRABAR Original", brand: "LÄRABAR", category: "bar", cho_per_unit: 30, sodium_per_unit: 5, calories_per_unit: 200, price_per_unit: 2.50, weight_g: 48, allergens: [], diet_tags: ["vegan", "gluten-free", "real-food"], description: "Dattes + noix, minimal ingrédients" },

                                                                                                        // ===== CHEWS =====
                                                                                                          { id: "gu-chews", name: "Energy Chews", brand: "GU Energy", category: "chew", cho_per_unit: 11, sodium_per_unit: 35, calories_per_unit: 45, price_per_unit: 0.50, weight_g: 10, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Chew individuel, facile à doser" },
                                                                                                            { id: "skratch-chews", name: "Sport Energy Chews", brand: "Skratch Labs", category: "chew", cho_per_unit: 10, sodium_per_unit: 30, calories_per_unit: 40, price_per_unit: 0.45, weight_g: 10, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Fraise naturelle, faible en sucre" },
                                                                                                              { id: "sis-go-chews", name: "GO Energy Bake", brand: "Science in Sport", category: "chew", cho_per_unit: 26, sodium_per_unit: 10, calories_per_unit: 140, price_per_unit: 1.80, weight_g: 50, allergens: ["gluten"], diet_tags: [], description: "Mini cake énergétique, texture moelleuse" },
                                                                                                                { id: "powerbar-chews", name: "PowerBar Energize Advanced Chews", brand: "PowerBar", category: "chew", cho_per_unit: 10, sodium_per_unit: 25, calories_per_unit: 40, price_per_unit: 0.40, weight_g: 9, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Format bonbon, facile en course" },

                                                                                                                  // ===== VRAIE NOURRITURE =====
                                                                                                                    { id: "banana", name: "Banane", brand: "Nature", category: "real-food", cho_per_unit: 27, sodium_per_unit: 1, calories_per_unit: 105, price_per_unit: 0.30, weight_g: 120, allergens: [], diet_tags: ["vegan", "gluten-free", "real-food"], description: "Fruit naturel, potassium + CHO" },
                                                                                                                      { id: "medjool-dates", name: "Dattes Medjool (3)", brand: "Nature", category: "real-food", cho_per_unit: 40, sodium_per_unit: 2, calories_per_unit: 160, price_per_unit: 0.80, weight_g: 60, allergens: [], diet_tags: ["vegan", "gluten-free", "real-food"], description: "Energie dense et naturelle" },
                                                                                                                        { id: "boiled-potato", name: "Pomme de terre (100g)", brand: "Nature", category: "real-food", cho_per_unit: 20, sodium_per_unit: 5, calories_per_unit: 85, price_per_unit: 0.20, weight_g: 100, allergens: [], diet_tags: ["vegan", "gluten-free", "real-food"], description: "Classique trail, avec sel si possible" },
                                                                                                                          { id: "rice-ball", name: "Rice Ball (riz + sel)", brand: "Maison", category: "real-food", cho_per_unit: 35, sodium_per_unit: 200, calories_per_unit: 140, price_per_unit: 0.40, weight_g: 80, allergens: [], diet_tags: ["vegan", "gluten-free", "real-food"], description: "Riz japonais salé, ultra digeste" },
                                                                                                                            { id: "white-bread-jam", name: "Pain blanc + confiture", brand: "Maison", category: "real-food", cho_per_unit: 40, sodium_per_unit: 150, calories_per_unit: 180, price_per_unit: 0.30, weight_g: 80, allergens: ["gluten"], diet_tags: [], description: "Snack classique ravitaillement" },
                                                                                                                              { id: "fig-bar", name: "Barre de figues", brand: "Nature", category: "real-food", cho_per_unit: 28, sodium_per_unit: 10, calories_per_unit: 120, price_per_unit: 0.60, weight_g: 40, allergens: [], diet_tags: ["vegan", "real-food"], description: "Figues séchées pressées, très digeste" },
                                                                                                                                { id: "salted-cracker", name: "Crackers salés (5)", brand: "Maison", category: "real-food", cho_per_unit: 15, sodium_per_unit: 300, calories_per_unit: 80, price_per_unit: 0.20, weight_g: 20, allergens: ["gluten"], diet_tags: [], description: "Sels + glucides simples, anti-nausée" },
                                                                                                                                  { id: "coca-cola-150", name: "Coca-Cola (150ml)", brand: "Coca-Cola", category: "real-food", cho_per_unit: 16, sodium_per_unit: 10, calories_per_unit: 65, price_per_unit: 0.50, weight_g: 150, allergens: [], diet_tags: ["vegan", "gluten-free"], description: "Glucides rapides + caféine, fin de course" },
                                                                                                                                  ];

                                                                                                                                  export function getProductsByCategory(category: Product["category"]): Product[] {
                                                                                                                                    return PRODUCTS.filter(p => p.category === category);
                                                                                                                                    }

                                                                                                                                    export function getProductById(id: string): Product | undefined {
                                                                                                                                      return PRODUCTS.find(p => p.id === id);
                                                                                                                                      }

                                                                                                                                      export function getProductsByBrand(brand: string): Product[] {
                                                                                                                                        return PRODUCTS.filter(p => p.brand === brand);
                                                                                                                                        }

                                                                                                                                        export function searchProducts(query: string): Product[] {
                                                                                                                                          const q = query.toLowerCase();
                                                                                                                                            return PRODUCTS.filter(p =>
                                                                                                                                                p.name.toLowerCase().includes(q) ||
                                                                                                                                                    p.brand.toLowerCase().includes(q) ||
                                                                                                                                                        (p.description || "").toLowerCase().includes(q)
                                                                                                                                                          );
                                                                                                                                                          }

                                                                                                                                                          export const BRANDS = [...new Set(PRODUCTS.map(p => p.brand))].sort();
                                                                                                                                                          