/**
 * Marques de référence pour l’autocomplétion (produits perso, shop).
 * Inclut les libellés catalogue courants (ex. Science in Sport, Aptonia (Decathlon)).
 */
export const REFERENCE_PRODUCT_BRANDS: readonly string[] = [
  "+Watt",
  "226ERS",
  "3Action Sports Nutrition",
  "Aptonia",
  "Aptonia (Decathlon)",
  "Amacx",
  "Andros Sport",
  "Apurna",
  "AqeeLab Nutrition",
  "Atlet Nutrition",
  "Authentic Nutrition",
  "Baouw",
  "Chimpanzee",
  "Clif Bar",
  "Cooknrun",
  "EAFIT",
  "Eric Favre",
  "Ergysport",
  "Etixx",
  "Fenioux Multisport",
  "GU Energy",
  "GU Hydration Tabs",
  "High5",
  "High5 Zero",
  "Hydratis",
  "Isostar",
  "LMNT",
  "Liquid I.V.",
  "Maurten",
  "Meltonic",
  "MuleBar",
  "MX3",
  "Näak",
  "NeverSecond",
  "Nomio",
  "Nuun",
  "Nutripure",
  "Osmo",
  "Overstim.s",
  "Pillar Performance",
  "Plasmaide",
  "PowerBar",
  "Precision Fuel & Hydration",
  "Punch Power",
  "Santa Madre",
  "Science in Sport",
  "SiS",
  "SiS Go Hydro",
  "Skratch Labs",
  "Saltstick",
  "Sponser",
  "Spring Energy",
  "STC Nutrition",
  "Stimium",
  "Styrkr",
  "Tailwind",
  "TA Energy",
  "Torq",
  "TORQ",
  "Veloforte",
  "Victus",
  "YAM Nutrition",
].sort((a, b) => a.localeCompare(b, "fr", { sensitivity: "base" }));
